<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>We are sorry(msg)</name>
   <tag></tag>
   <elementGuidId>da65093c-cee4-4389-936a-446732f960d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wizard']/div[2]/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>cc12a03a-e16e-424d-acaa-664672dfeee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We are sorry! The given email address has not been registered with StudySmart. Please enter a registered email address.</value>
      <webElementGuid>a8a854a7-3514-4e56-8a4f-1020c4dccfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wizard&quot;)/div[@class=&quot;alert alert-danger  text-center msg&quot;]/strong[1]</value>
      <webElementGuid>3d9a1365-7b3a-4474-9a54-c6ef020478b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wizard']/div[2]/strong</value>
      <webElementGuid>89aecb7a-0a81-4be0-8a1f-240c50b4ab4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>f9630f67-b725-448e-9696-6d57bc60c60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'We are sorry! The given email address has not been registered with StudySmart. Please enter a registered email address.' or . = 'We are sorry! The given email address has not been registered with StudySmart. Please enter a registered email address.')]</value>
      <webElementGuid>62815a1f-5993-4b19-8f56-dc20a389d233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
