<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Topic</name>
   <tag></tag>
   <elementGuidId>b74926f7-6ff2-415b-951f-a8aa9f06e654</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='topic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c1373693-2d84-474d-bd2b-a103c9f72aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>112b008c-9391-4b1c-ad4f-43356942eeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>c6fa53e9-f402-41f0-92c0-1822ae0f42dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>2c01151a-e35b-4304-8bf9-ad93725c42ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Topic--Grammar MCQPunctuation &amp; EditingVocabulary MCQGrammar ClozeVocabulary ClozeSynthesis &amp; TransformationComprehension</value>
      <webElementGuid>2672230d-2821-4b1a-b1ab-c856ff137d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topic&quot;)</value>
      <webElementGuid>d05c38c1-61ff-4208-9186-ee23c1165280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='topic']</value>
      <webElementGuid>2665f3b5-cde6-45d1-b987-00a4051de47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>8bcc6896-3772-4117-a9be-7bdde0716e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'topic' and @name = 'topic' and (text() = '--Select Topic--Grammar MCQPunctuation &amp; EditingVocabulary MCQGrammar ClozeVocabulary ClozeSynthesis &amp; TransformationComprehension' or . = '--Select Topic--Grammar MCQPunctuation &amp; EditingVocabulary MCQGrammar ClozeVocabulary ClozeSynthesis &amp; TransformationComprehension')]</value>
      <webElementGuid>161ab887-5be3-4132-bd4f-683054c60f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
