<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_14</name>
   <tag></tag>
   <elementGuidId>18371606-3b10-46b8-b094-ab09ecc6ed63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.info-box-number.quest_count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultShow']/div[2]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21f10ccb-17d7-45a1-aa30-4d4709f0b6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info-box-number quest_count</value>
      <webElementGuid>c8b5046f-c4b6-478c-954c-59241ba5638f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>MCQ</value>
      <webElementGuid>5a794879-2d4e-49a8-8bfe-62d31e1a2b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>ea90e9c9-26e6-4fda-adda-59a97413c6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultShow&quot;)/div[@class=&quot;col-12 col-sm-4 col-md-4 col-lg-4&quot;]/div[@class=&quot;info-box shadow mb-3&quot;]/div[@class=&quot;info-box-content&quot;]/span[@class=&quot;info-box-number quest_count&quot;]</value>
      <webElementGuid>8bc3edcc-b524-4c4a-9a37-f6bc2e4c7ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultShow']/div[2]/div/div/span[2]</value>
      <webElementGuid>b54c8ef9-cf5b-4e2b-97b3-7c6963f77ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]</value>
      <webElementGuid>8e7d6915-5abd-43c8-ac45-f5810eb79170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '14' or . = '14')]</value>
      <webElementGuid>1fee4788-9876-4562-8252-1157aa60cd5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
