<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keyword_1</name>
   <tag></tag>
   <elementGuidId>6e40ec85-c721-46e2-89fd-0b44d645d90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[653]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.note-btn.btn.btn-light.btn-sm.keyword-btn.s-btn.key-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba7edfd2-4a93-4ee2-be0e-4012718fa10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3643c806-65c9-486e-a05a-fb14264bd121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-btn btn btn-light btn-sm keyword-btn s-btn key-btn</value>
      <webElementGuid>09aea7e5-a3b9-418d-b6ea-f66f79848834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d3906a1a-0d0e-4901-9fc5-fd3dbc03f728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Keyword</value>
      <webElementGuid>cb94adec-4111-429b-912a-a0888b40e012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Keyword</value>
      <webElementGuid>2140de90-5263-42c7-9980-f9bcea6f54ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keyword</value>
      <webElementGuid>b6bc6792-ee43-4c5e-9604-3aaa67ede355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;answer-tag&quot;)/div[@class=&quot;note-editor note-frame card&quot;]/div[@class=&quot;note-toolbar card-header&quot;]/div[@class=&quot;note-btn-group btn-group note-mybutton&quot;]/button[@class=&quot;note-btn btn btn-light btn-sm keyword-btn s-btn key-btn&quot;]</value>
      <webElementGuid>e0cd70db-a3a7-4c7d-beee-32fadc95bd6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[653]</value>
      <webElementGuid>145fa7a2-92b3-40f2-9dbf-7ec142f69455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='answer-tag']/div[2]/div[2]/div[8]/button</value>
      <webElementGuid>9fd76f6f-aeb5-4c9a-81cc-5bcafd4a9bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[2]/div[2]/div[8]/button</value>
      <webElementGuid>a3f74813-1453-4ae9-b49d-3a7c41bf3f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Keyword' or . = 'Keyword')]</value>
      <webElementGuid>642373f4-bb67-4a71-aec8-6dc427e5b196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
