<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputkeyword_1</name>
   <tag></tag>
   <elementGuidId>f8042b05-1fa5-45a8-b295-fa4ea15d00ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keyword_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keyword_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a097378a-50ac-4df8-97e6-08e3e70f97a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a971f4f9-514d-4088-a52c-6404669dd56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>answer-hint answer-dash explain-answer ml-2 mr-0 bg-transparent d-inline-block w-auto</value>
      <webElementGuid>299749be-fa7d-4588-b5e5-d05236bdbe7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword_1</value>
      <webElementGuid>2d13cf38-1b69-4476-a924-855d650833db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_1&quot;)</value>
      <webElementGuid>6c1688a6-70c6-4df7-8af7-8e26b0dcee2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keyword_1']</value>
      <webElementGuid>867c18b6-6c2d-4d32-bfa1-ad3bb2fe4db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dashinput_1']/input</value>
      <webElementGuid>1ae8fe2b-f7e8-4294-9f49-74e9787fb82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span/input</value>
      <webElementGuid>605549e0-5ae9-45be-bf5c-43862aa3a440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'keyword_1']</value>
      <webElementGuid>c8dba059-59a2-4eb6-bd58-b6827c7f0c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
