<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Topic</name>
   <tag></tag>
   <elementGuidId>ff4235a8-3083-4f72-abdc-f738e50d78ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='topic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f85c489a-5eba-4a54-91e3-636a37822d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>dbd6b49b-da96-421d-b163-90fb793c1125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>284c4602-c9c3-4c80-a166-ef66b462ace0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c97cfc88-d0a0-449a-816b-e5301c814f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grammar MCQVocabulary MCQGrammar ClozeVocabulary ClozePunctuation &amp; EditingSynthesis &amp; TransformationComprehension</value>
      <webElementGuid>e233de19-1025-4529-a32b-1d6da796355d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topic&quot;)</value>
      <webElementGuid>84713a07-9eaf-44f4-977d-95534d943327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='topic']</value>
      <webElementGuid>3d8efae1-c03e-440d-b099-32b2c40abad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[5]/div/select</value>
      <webElementGuid>f3511d32-4046-48ca-b049-3f83eeb7f1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>c24a6c24-dc6e-4cd4-acc5-e1d82fdf039a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'topic' and @id = 'topic' and (text() = 'Grammar MCQVocabulary MCQGrammar ClozeVocabulary ClozePunctuation &amp; EditingSynthesis &amp; TransformationComprehension' or . = 'Grammar MCQVocabulary MCQGrammar ClozeVocabulary ClozePunctuation &amp; EditingSynthesis &amp; TransformationComprehension')]</value>
      <webElementGuid>89f25d9a-2ede-4da6-b490-ecc6a368235d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
