<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mode of Promo</name>
   <tag></tag>
   <elementGuidId>58e79778-da79-4a20-a8f1-da47c8f9acad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promo_mode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promo_mode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a375720b-96ab-4169-85ef-a58f22d928af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>typeahead form-control</value>
      <webElementGuid>e8721d77-105a-49ba-a83e-57d5989ea2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>datalistOptions</value>
      <webElementGuid>4dd80b74-2415-4f72-a1e7-ffe77eb18210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promo_mode</value>
      <webElementGuid>6895730e-ea49-4fc0-8bc2-ae38db71548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promo_mode</value>
      <webElementGuid>1c2cf46a-8c48-41ce-a4a9-e0dd47b47d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to search...</value>
      <webElementGuid>c8cbad7c-1a6d-453e-81d3-be7eca5b3df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo_mode&quot;)</value>
      <webElementGuid>825e8121-210c-41e4-b041-07993a5551b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promo_mode']</value>
      <webElementGuid>d2579d4e-005e-4932-8f24-9361fe33b48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>fbb90e84-dd29-46d9-a2a3-0ee9e5457191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'promo_mode' and @id = 'promo_mode' and @placeholder = 'Type to search...']</value>
      <webElementGuid>11d99f27-6a63-4106-af7c-956b1afac791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
