<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>promo_code</name>
   <tag></tag>
   <elementGuidId>5e6d48f3-d995-40d6-9edf-d846339a2963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'text' and @name = 'promo_code' and @id = 'promo_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promo_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dedbe03f-d43c-4269-9fa7-6e42eeae6bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fbe62bf-06bb-40b4-b1e0-f2690d5d942d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promo_code</value>
      <webElementGuid>14868b3c-428f-47cc-b06e-b4624b0ae9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promo_code</value>
      <webElementGuid>63a60d8e-15b9-4f26-8d0c-8ab79ed6da86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ac21a447-5fcf-4b58-8cc5-3cc06da28a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo_code&quot;)</value>
      <webElementGuid>f8e1cbcb-cf67-402f-a77b-2d62e9a9bc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promo_code']</value>
      <webElementGuid>8c295371-fcea-4c7e-a1f5-f00fd5d10d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>e3222c8b-7cd7-4ac7-8ae4-8dfbc217f55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'promo_code' and @id = 'promo_code']</value>
      <webElementGuid>fb69532c-6998-4944-b30a-7bb017bf76c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
