<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P1_Actual_Price</name>
   <tag></tag>
   <elementGuidId>6c404715-5b68-4e7e-a119-b07b0e09d968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13067f7a-6427-4b8c-93d7-846ffc85b645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4ec9f7ff-6fef-4d5e-b759-17231097821a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>43258620-1afd-4286-a2e3-3b21b2091542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>49.90</value>
      <webElementGuid>b17ad61c-d14a-4cd2-b482-b97a4657f20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_1_1</value>
      <webElementGuid>2d15d8d7-e3cc-4135-be7e-0a4436854918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_1_1</value>
      <webElementGuid>cd3838d5-6cd7-40a7-a056-4f0fd8cadad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_1_1&quot;)</value>
      <webElementGuid>63f11fe3-406e-479a-b192-9b3c94c8cc59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_1_1']</value>
      <webElementGuid>e25a08fa-172e-453d-a301-b403ae93a3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>d496ac7c-88b3-4ee2-acc1-498593f07e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'actual_1_1' and @id = 'actual_1_1']</value>
      <webElementGuid>e5489aeb-6b5f-45fc-988f-1d4776fea672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
