<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P1_Offer_Price</name>
   <tag></tag>
   <elementGuidId>314e40f3-591f-490f-981e-7a0b27707a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58e52b5e-6b0d-44a1-b07e-893ffd524649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>31d32ca0-b78c-4124-ad22-9c862f70f347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>f4a7372a-05fc-4fa0-9d96-4c98f42ecb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24.90</value>
      <webElementGuid>78f0eb82-ad33-4b6c-a864-50f81072e4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_1_1</value>
      <webElementGuid>f8f7881c-30b0-47af-8259-0176ba836a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_1_1</value>
      <webElementGuid>352d445d-5788-4ebb-9474-dc922106bdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_1_1&quot;)</value>
      <webElementGuid>2fb8b1d8-d140-4124-b95f-28d7ef98a850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_1_1']</value>
      <webElementGuid>4155e466-c8b6-43d2-84de-f1dcdb90eaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>561b5cc6-0e4d-4e57-9a2a-f20b88394c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'offer_1_1' and @id = 'offer_1_1']</value>
      <webElementGuid>989c59ac-c5b2-44a6-adda-6ee0990c74e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
