<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P2_Actual_Price</name>
   <tag></tag>
   <elementGuidId>d8c835ed-873f-4906-bf8b-ba3853888f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_2_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_2_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92184239-24d2-47bf-bc0e-923c4640a6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ae84fc70-c67e-4f11-8fbf-ce270c121991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>29d97668-62d2-44e9-8c72-b36640103b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>74.90</value>
      <webElementGuid>51386ca7-6c78-4b92-8c7a-498bba2582c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_2_2</value>
      <webElementGuid>1fcfbbab-492f-4ef0-8306-112e5b4ca403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_2_2</value>
      <webElementGuid>79c3678c-4bc0-41b7-9e96-3feb926f12c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_2_2&quot;)</value>
      <webElementGuid>d63aa9b5-121d-4766-94e2-d9d79b2ce9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_2_2']</value>
      <webElementGuid>48a7be10-2129-4580-9a6b-45ea479297db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>44b55528-6822-4c01-8e2e-7c0d8966de0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'actual_2_2' and @id = 'actual_2_2']</value>
      <webElementGuid>7e2008a6-4f64-47d7-a047-11269b1ffb22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
