<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P2_Offer_Price</name>
   <tag></tag>
   <elementGuidId>cf13f179-5bb9-4221-bb24-b1e8a489453b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_2_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_2_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea6fa19e-9a6d-4a2b-8354-52bf27a367b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6f985fd5-caee-46ab-a5bc-7acc9f922b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>b4f7ab17-0cf9-496c-8674-2ac7c2413ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24.90</value>
      <webElementGuid>7548bfab-200d-4938-bc20-cae862545a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_2_2</value>
      <webElementGuid>b4597c95-f776-4c47-83aa-6fe8e9cc3a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_2_2</value>
      <webElementGuid>1ff4af9b-a2f5-4535-a3a8-44c4460f1163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_2_2&quot;)</value>
      <webElementGuid>3f69b282-d1e3-42a0-b001-2269b5a3f3df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_2_2']</value>
      <webElementGuid>7955a3b2-f462-4e51-8684-457b1f0c9800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>4d1a2f46-03de-417e-b8b7-5d3c48276f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'offer_2_2' and @id = 'offer_2_2']</value>
      <webElementGuid>29b26a36-ea0d-4a15-90f6-728ae974fdff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
