<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P3_Action</name>
   <tag></tag>
   <elementGuidId>6a8ba8bb-2012-4ab6-a293-34bcbed12c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_3 > i.fa.fa-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='edit_3']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7bf0d623-8af4-4741-827e-93696440cc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>3eaf12ae-dc24-4978-8ab5-503376fd87ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>1cd4be60-bea4-4df5-b21b-31b12c9ee468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>39a308ff-fd85-4d3b-be14-c7141bdc182d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>deb2dd39-600b-4607-9943-d36a86475dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip307040</value>
      <webElementGuid>47383f32-8b03-48ef-bbd6-5cf2f97bd72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_3&quot;)/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>e2d92729-95a6-4baf-bf26-3a0934c83862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='edit_3']/i</value>
      <webElementGuid>756ca89b-fc1e-49d7-81d4-7c2b2336435c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/a/i</value>
      <webElementGuid>b3a3a08a-81be-463d-b3e4-288c1e5ca292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
