<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P3_Actual_Price</name>
   <tag></tag>
   <elementGuidId>76c8ff45-7bde-444c-b5d5-dc433f4594a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_3_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_3_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>540acd69-1e0e-4c51-a45f-1409417fc5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8549d37e-43b1-479a-a655-dfbff7ef4389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>371dceb2-40ad-405e-8828-6de8cb63ffb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>249.90</value>
      <webElementGuid>30315da8-485c-4fc4-8f7f-4c7b9899ab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_3_3</value>
      <webElementGuid>847167ec-066e-4e55-b0d4-bf1f11788a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_3_3</value>
      <webElementGuid>9701314b-74b3-475a-89ac-6729c7799e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_3_3&quot;)</value>
      <webElementGuid>f41e64dc-d92a-4c39-87d3-1b1c111b7397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_3_3']</value>
      <webElementGuid>52fec9b2-7deb-42e8-a97e-9aa619c2cf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>2c3ae3f4-3a5b-4670-85d6-0117d908004e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'actual_3_3' and @id = 'actual_3_3']</value>
      <webElementGuid>3ea77d8c-c092-4aaa-b483-fb56b38a6a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
