<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P3_Offer_Price</name>
   <tag></tag>
   <elementGuidId>5ef3af75-e3e6-44c1-8cd6-07481e439cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_3_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_3_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1da617c-7f33-4899-9345-a0861f70f34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7065a148-9db8-4456-ad9f-7bfb6b543ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>51e1f08a-d1dd-4a7d-9bf3-86c10fcb32cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0f0696d4-5d83-4cb1-ac40-42dfc1ec4f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_3_3</value>
      <webElementGuid>d47db11f-b4ec-434e-b830-6391bd01d08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_3_3</value>
      <webElementGuid>aae724d8-0eb4-4c60-a87a-3c70f285b48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_3_3&quot;)</value>
      <webElementGuid>c5d8ffd6-f909-4095-b76f-e461aa91895f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_3_3']</value>
      <webElementGuid>c0857dab-74e1-4aea-b0c0-de902d59209f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>cf63cf08-85fc-4be1-96a6-f97cb7768490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'offer_3_3' and @id = 'offer_3_3']</value>
      <webElementGuid>cb367afd-c69e-4b00-b2f4-a1044e1d46d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
