<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P3_Update_button</name>
   <tag></tag>
   <elementGuidId>9f60a764-8d9d-4eac-b7ba-e39feaa39ffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#update_3 > i.fas.fa-paper-plane</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='update_3']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a1bc3b85-33d5-473d-b25a-46c9ba341fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-paper-plane</value>
      <webElementGuid>2a9649f6-d39f-4e5d-9417-5c3605abd527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update_3&quot;)/i[@class=&quot;fas fa-paper-plane&quot;]</value>
      <webElementGuid>eb64eb33-948b-499c-ad2a-f76fb0532002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='update_3']/i</value>
      <webElementGuid>a284f854-90b9-42c7-81fa-27d36dcb015e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/a[2]/i</value>
      <webElementGuid>4272c1c9-78e5-4386-b11c-c275db38dc74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
