<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P4_Actual_Price</name>
   <tag></tag>
   <elementGuidId>7497da47-5cab-4bb0-b95d-745a0cb643c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_4_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_4_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f8d7847-3cb3-4f53-96a6-e498e8dd9372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5facb01c-5a1c-4533-8324-fa71b57f7253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>b9d7abe0-278e-4613-84fb-8f2aaac0922a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>249.90</value>
      <webElementGuid>4764f7f9-31c9-4a47-828e-3458098e1eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_4_4</value>
      <webElementGuid>75b4c11c-e25a-4cef-a5bb-2cb00097d020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_4_4</value>
      <webElementGuid>8bc0fba7-e647-47d4-9710-31f5deac0783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_4_4&quot;)</value>
      <webElementGuid>14acd6e4-1f93-4d8f-86c6-edcde99b55a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_4_4']</value>
      <webElementGuid>60b90a7a-d0e5-4421-af86-f51e479b2ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>197665e4-daae-4cd1-97cb-a76499f9d8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'actual_4_4' and @id = 'actual_4_4']</value>
      <webElementGuid>1cd22aa2-f214-417c-92f2-cce9c4cdc2de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
