<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P4_Action</name>
   <tag></tag>
   <elementGuidId>e5315487-659c-4617-991f-9090645259e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_4 > i.fa.fa-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='edit_4']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2f8a212b-4186-4050-9963-887525076b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-edit</value>
      <webElementGuid>a20c4607-39a7-4b93-b240-c743b4b16a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>37ede144-b7e1-4607-86c8-601da6a3251a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>e1d14dae-2316-4254-9a14-b829be5af231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>fb8ed64a-0039-4f6d-8fd1-8c3193853cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip256478</value>
      <webElementGuid>3266dde4-6796-44c6-bdfb-5a667e8cdfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_4&quot;)/i[@class=&quot;fa fa-edit&quot;]</value>
      <webElementGuid>e0cdc59a-94be-494b-93c3-b1ab0de57f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='edit_4']/i</value>
      <webElementGuid>aabfe0aa-b878-46a2-93b6-fdf0d07973df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/a/i</value>
      <webElementGuid>0585f712-7fa0-4dd1-814c-3d2e481ee48d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
