<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P4_Offer_Price</name>
   <tag></tag>
   <elementGuidId>acb1d67c-5c53-40f6-8668-a0f5cca539f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_4_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_4_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cceddf5-0e07-41bd-a1a4-5b1d144ff674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>04ac40be-8367-4869-924b-fdd04abbca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>3a421aad-8562-4def-a76f-19b17cf04834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5a48c287-837b-4406-8cd7-80b2aa13430a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_4_4</value>
      <webElementGuid>f738d762-2f15-413a-aa91-0fd052a749b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_4_4</value>
      <webElementGuid>6450538c-f754-4ef4-9b18-41f1a81af33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_4_4&quot;)</value>
      <webElementGuid>a2a65dce-a475-461e-868e-71ae6a2a075e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_4_4']</value>
      <webElementGuid>6168c67f-bf16-4a91-8d5f-0500d7c36605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>4352a092-7542-49e0-b7ab-83d263655aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'offer_4_4' and @id = 'offer_4_4']</value>
      <webElementGuid>4ef0cc5c-367e-4ea9-a1d7-802a010ddc86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
