<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P5_Actual_Price</name>
   <tag></tag>
   <elementGuidId>ebbd5749-7bd0-4520-9030-3af53b916f31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_5_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_5_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c379868-3105-4a5c-9df8-4675f4695f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>cb154027-d9cd-4ac5-acc4-119bf7563bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>d2ae1f04-f311-4972-9797-9eefb2afa745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>349.90</value>
      <webElementGuid>e2a4a5b8-adb0-4e9a-b481-c3aaf4454436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_5_5</value>
      <webElementGuid>3e34fdba-f36c-4923-b2af-410c860afdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_5_5</value>
      <webElementGuid>087847d5-7311-49f9-8b74-2e0202e91640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_5_5&quot;)</value>
      <webElementGuid>84e69913-7809-423f-b7cf-7023170e15d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_5_5']</value>
      <webElementGuid>71a816c7-3b4a-448c-834c-82b31dce3c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>0dbb5e13-8ffd-4b50-8692-faac0859fe58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'actual_5_5' and @id = 'actual_5_5']</value>
      <webElementGuid>bf685aea-b8cb-4d3f-9e94-c9d153939b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
