<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P5_Offer_Price</name>
   <tag></tag>
   <elementGuidId>103b91e3-99df-49ca-ad48-03e04ec77929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_5_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_5_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2538c758-f381-435f-acf9-17ad327bd13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4f2d4502-76dd-44ed-ba15-1b9df8ad96f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>3060f2fe-f34a-48c7-a05b-d7848118b155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>31b90845-26f9-4c01-a3fc-81581bdab592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_5_5</value>
      <webElementGuid>e75b31ca-36c9-45ee-8aad-430e2112c1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_5_5</value>
      <webElementGuid>508ca25b-8cc1-45f7-a823-ffb92f3d304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_5_5&quot;)</value>
      <webElementGuid>892baf93-01b9-4547-8be7-a494d807e8fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_5_5']</value>
      <webElementGuid>1fecb0d8-46e3-46ec-8951-be3f5c867ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>414385d6-0a7c-4559-95e4-57f82bdac9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'offer_5_5' and @id = 'offer_5_5']</value>
      <webElementGuid>1f861a5d-d7c9-4508-84fb-e2428a7979f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
