<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P5_Update_button</name>
   <tag></tag>
   <elementGuidId>5cfb9243-6fc7-4ee0-9897-836d4ddb5e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#update_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='update_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a7d2a70-6a49-46b2-bddf-e80402d7b69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>2d2e9215-0873-4ec2-b598-73a6957e46eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>370e5cea-8d34-45f9-bad2-b62fc859b948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>update_5</value>
      <webElementGuid>82d79ba5-4f17-420b-bb64-1abb04b9ecc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>update_primary(5,5);</value>
      <webElementGuid>9c036bf9-a9bd-47a8-bb31-8ca65adea5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update_5&quot;)</value>
      <webElementGuid>bfcc1b84-6b2e-4652-a111-53a916799688</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='update_5']</value>
      <webElementGuid>7dadc792-86dc-4c7c-8e32-5555dfb89a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[10]</value>
      <webElementGuid>d371d22a-ccf7-4a42-ac29-0156afb30f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/a[2]</value>
      <webElementGuid>72e538f8-339c-4fff-8c5d-8a6e9bd1672a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'update_5']</value>
      <webElementGuid>e393f576-40df-422f-b611-fb30b7ebb27c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
