<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P6_Actual_Price</name>
   <tag></tag>
   <elementGuidId>5ed5b56b-0034-47eb-9b73-ff207e812619</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_6_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_6_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21b439e4-ef28-4cd9-8a64-0e815465d1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f8097073-76de-4141-8792-8c5b0854c0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>a91fffae-49bc-43bd-baf5-70cdf7969a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>349.90</value>
      <webElementGuid>c784786e-7ccb-4a93-b78b-be7e984025bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_6_6</value>
      <webElementGuid>da084811-d743-47f9-94b5-f95f4967e90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_6_6</value>
      <webElementGuid>94d9e253-176f-4745-a0ef-082c96c904fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_6_6&quot;)</value>
      <webElementGuid>08d5b7d9-d700-4283-b3f1-071d1ff1e49b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_6_6']</value>
      <webElementGuid>6c2554c2-a627-436e-b51c-667de3026026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>4612dd75-cf28-4b66-8f33-80540c3438a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'actual_6_6' and @id = 'actual_6_6']</value>
      <webElementGuid>84dee5b9-098f-4ba1-abe1-a7885b6facdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
