<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P6_Offer_Price</name>
   <tag></tag>
   <elementGuidId>98381dea-477f-4df7-b0c7-02486db7eed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_6_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_6_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51b52220-cb1e-4016-aab2-18a475c49048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9c6b96b8-ac2f-406b-85fe-b5a307a01432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control decimal</value>
      <webElementGuid>17ebd462-f416-4e8e-89a8-bf33c4172c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>038b22fa-7c18-4302-b7c9-a77ae72864ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer_6_6</value>
      <webElementGuid>20aa592a-a0fe-4cca-b7cb-8b1e38921f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_6_6</value>
      <webElementGuid>1bf87625-5d82-4e75-a0e0-760996e33172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_6_6&quot;)</value>
      <webElementGuid>84a0c370-c960-4a7b-a1f2-e0834da29eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_6_6']</value>
      <webElementGuid>b6eb9cc8-fb8a-424e-8533-4025611fe3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>6947e98a-862e-49fb-bd63-85d55e77b08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'offer_6_6' and @id = 'offer_6_6']</value>
      <webElementGuid>da86ebdd-2d37-4493-99fd-8aa817ad7860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
