<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>P6_Update_button</name>
   <tag></tag>
   <elementGuidId>cd11b6a7-ccd8-4084-b65b-d596c0db2537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#update_6 > i.fas.fa-paper-plane</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='update_6']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5105e6bb-d61b-49b7-bfaf-3b3fb17bf786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-paper-plane</value>
      <webElementGuid>e4351c20-2532-462c-b12d-d78e9534a802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update_6&quot;)/i[@class=&quot;fas fa-paper-plane&quot;]</value>
      <webElementGuid>05378359-e0a0-43dd-9fcb-85996bdeb7d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='update_6']/i</value>
      <webElementGuid>1f1d4c29-bcd6-4a9b-8746-86b51603a580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[3]/a[2]/i</value>
      <webElementGuid>5164eef1-530a-4fe4-bb61-ce11132036a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
