<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manual_id</name>
   <tag></tag>
   <elementGuidId>582d74c6-b217-4645-a3f7-152e824cab93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manual_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manual_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d136ebe-29aa-46d8-bea2-3d740cae9e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1f6e4e6-32a4-4e8b-987e-d951f66d383f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f8875571-daa7-4891-be60-eabbdc69996a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manual_id</value>
      <webElementGuid>e5dc4a0e-228a-47a0-9e0b-676582d43ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manual_id</value>
      <webElementGuid>d6d37c0b-cff1-4efd-b5bc-f80e41abf636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manual_id&quot;)</value>
      <webElementGuid>6933babb-eec5-4d98-b24f-7c9ea44bf962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manual_id']</value>
      <webElementGuid>5d52905a-b47c-4530-9d7f-08f8e02c851c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[4]/div[3]/div/div/input</value>
      <webElementGuid>1e561480-3e41-45d8-b535-16d70977b34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/input</value>
      <webElementGuid>411980aa-3711-4ad5-9df6-a393642a3945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'manual_id' and @id = 'manual_id']</value>
      <webElementGuid>eb999277-dabb-4881-b590-2c1b4be3f17f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
