<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1.SS_Dashboard</name>
   <tag></tag>
   <elementGuidId>94d9d8a3-373e-495f-a8d0-b66850215dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dashboard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class=&quot;nav-link dashboard&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6a82f4b6-cdb4-4a22-b621-b8c618074d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>eda92b1b-7ff4-40e2-bca3-0a5802c35aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Dashboard
                                </value>
      <webElementGuid>273837e6-e322-41cd-a64f-5fa0a8e776d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)</value>
      <webElementGuid>905069bd-1602-44ca-9b18-51b1fa5c946a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='dashboard']</value>
      <webElementGuid>68ccd465-6fc8-4955-8b07-32a441120756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='bgTransparent']/div/div[4]/div/div/nav/ul/li/a/p</value>
      <webElementGuid>4958373c-a179-47b2-9631-d5da2a1fd107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>25de5d64-c3c7-4855-870e-1afb0d2a181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'dashboard' and (text() = '
                                    Dashboard
                                ' or . = '
                                    Dashboard
                                ')]</value>
      <webElementGuid>40c4d198-4d08-4daa-ac59-6eae74e1f1a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
