<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Blank</name>
   <tag></tag>
   <elementGuidId>c247ca3e-580b-4b5c-855b-9f31cd5b5280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[177]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.note-btn.btn.btn-light.btn-sm.dash-btn.s-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1173f51f-3b3f-4f3a-8d86-4844e037ae8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e157da77-a7ca-48a2-8bac-c3965ea593be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-btn btn btn-light btn-sm dash-btn s-btn</value>
      <webElementGuid>f201709a-96e8-462d-a421-520914915a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>52f8c4c2-9098-47f2-a3a1-4b6f47efa47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Blank</value>
      <webElementGuid>1a107d0f-9a1b-447f-b43a-035d2f24f74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Blank</value>
      <webElementGuid>b88afed0-81b1-4f11-b544-25c47878d628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blank</value>
      <webElementGuid>43fe1355-619b-4243-b837-20874d0cd3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-main&quot;]/div[@class=&quot;template_section shadow&quot;]/div[@class=&quot;note-editor note-frame card&quot;]/div[@class=&quot;note-toolbar card-header&quot;]/div[@class=&quot;note-btn-group btn-group note-mybutton&quot;]/button[@class=&quot;note-btn btn btn-light btn-sm dash-btn s-btn&quot;]</value>
      <webElementGuid>6a0d3f73-09ec-4cea-84f0-935c7543187a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[177]</value>
      <webElementGuid>135f4fad-b690-4388-b539-8a2ae74bf1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[2]/div[2]/div[9]/button</value>
      <webElementGuid>2755ac7a-4bf2-4620-9b37-eb51002a484f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>7624ecbe-a58f-408d-bac9-c5715932c994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Blank' or . = 'Blank')]</value>
      <webElementGuid>79808729-4bb2-4d17-bda1-66448755d31b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
