<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputshort_1</name>
   <tag></tag>
   <elementGuidId>3e3b386e-f361-4142-bbac-6765e6876b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='short_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#short_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36e79f4d-3e75-4961-8f10-b2bbd10af890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74c06da6-ecb2-44cf-b204-4d0cef19356d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>answer-hint answer-dash short-dash ml-2 mr-0 bg-transparent d-inline-block w-auto</value>
      <webElementGuid>aa84a5f8-23da-4533-bf12-bcb802199779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>short_1</value>
      <webElementGuid>ac967316-fe0a-431e-8f44-a3356ad584e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;short_1&quot;)</value>
      <webElementGuid>0635b10c-683a-4662-99f4-fab611486912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='short_1']</value>
      <webElementGuid>1d1aa103-e33c-48b5-8ea0-5f5f687cd0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dashinput_1']/input</value>
      <webElementGuid>d58f4e0f-4c10-4b5c-a743-2445f7180692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>ee24085e-ea52-4bed-a882-5af7007783da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'short_1']</value>
      <webElementGuid>e0a26475-7c40-4246-ba69-98a27f1b317c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
