<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputshortmark_1</name>
   <tag></tag>
   <elementGuidId>99f49e40-4bed-4e57-b715-75bce1d756d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shortmark_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shortmark_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7e28c3e-370a-4a7b-bf55-02a25298f8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fddfcef3-b7e5-4593-8aab-1a339d26f789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>answer-hint answer-dash key-mark edit-key-mark ml-0 mr-2 bg-transparent d-inline-block w-auto</value>
      <webElementGuid>8d80d3de-8b51-4834-b6f2-6287b8978884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mark</value>
      <webElementGuid>9dde3177-0650-43c9-822c-61b42b32a530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8d7c6e25-b0e8-4e08-9378-0c1663d626ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b6b0cd54-e8fb-4ed4-919a-54143ecf1c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shortmark_1</value>
      <webElementGuid>50010150-bfd1-4e2c-a4b2-a645ae7bedd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>08ec0d9b-6a56-4373-8da8-10de6bf29e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselectstart</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>e646cd27-0ca9-4245-8747-d9669f3e4aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>546d2783-7365-4dfe-ac27-b7812db517d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>63f02340-0cae-4d50-a439-44532faa17b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>a16d17e2-9f02-496c-bea5-922d8f98c4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrag</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>2afca0e8-9d78-4ef7-8e0d-260b44393008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>77928389-25e6-42bd-8c87-51fde679286a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off/</value>
      <webElementGuid>0deba35d-f2b4-4dbe-979c-6c5d1daae5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shortmark_1&quot;)</value>
      <webElementGuid>93caf7f8-899a-475c-ad8f-ec1617ff8da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shortmark_1']</value>
      <webElementGuid>83050e3f-0031-4ea3-ba52-8ec6edb2b7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dashinput_1']/input[3]</value>
      <webElementGuid>f5a7bbd3-0dd3-4425-92cb-5b4fde56a901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input[3]</value>
      <webElementGuid>640a31c5-cf11-446e-8b43-5ae193e97547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Mark' and @id = 'shortmark_1']</value>
      <webElementGuid>c943b208-3297-4541-a204-7a5d4b32f9bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
