<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_profile_icon</name>
   <tag></tag>
   <elementGuidId>4a8f702a-aaf3-4639-920d-c4d267acb181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userProfile']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.profile_icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>54189b6f-ef92-4382-971f-e8a093d78d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qc.studysmart.sg/images/691518629.jpg</value>
      <webElementGuid>6b072a24-c99b-4439-8b03-de5a37cc819a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile_icon</value>
      <webElementGuid>1f31266b-baa5-4036-ac82-cd931578afcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userProfile&quot;)/img[@class=&quot;profile_icon&quot;]</value>
      <webElementGuid>492e5237-d2c5-4c84-930a-81a77148196b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userProfile']/img</value>
      <webElementGuid>e1082cb9-9cbb-4a79-a74b-9ceb1937943c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://qc.studysmart.sg/images/691518629.jpg')]</value>
      <webElementGuid>4dc74de9-54bf-4733-ae5d-c7807a0800e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>52569c04-48ad-4c64-9899-5aa8ceaf8694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qc.studysmart.sg/images/691518629.jpg']</value>
      <webElementGuid>c2194720-197b-4954-8b69-8031af5b2fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
