<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Temp question</name>
   <tag></tag>
   <elementGuidId>b3a714a2-0169-443f-bf74-e16dda634aed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.note-editable.card-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div/div[2]/div/div[2]/div[3]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7eabba0f-3b71-43e4-ab62-01df8cd24fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editable card-block</value>
      <webElementGuid>6067b8dc-0691-4aa0-8df4-378bfac9cc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2d2da35-2155-4c2f-9b7e-f686dcf19288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>3c2dd5be-2d15-4265-82b6-a4cfd2bbf801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51694981-9bd0-4704-b272-669773ff7270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65022926-b9a0-40f6-9c22-6cc27a9fbbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a7bfe85-0a7a-43cd-b1a3-e5c12abb7bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Temp question</value>
      <webElementGuid>c4af514f-42ab-4162-87eb-ed667f818bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-main&quot;]/div[@class=&quot;template_section shadow&quot;]/div[@class=&quot;note-editor note-frame card&quot;]/div[@class=&quot;note-editing-area&quot;]/div[@class=&quot;note-editable card-block&quot;]</value>
      <webElementGuid>6963958a-a71b-4670-9153-790d5b206e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[2]/div[3]/div[3]</value>
      <webElementGuid>b0dde56d-4356-489d-ae69-183d0fcbe1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>87c2cfc8-3835-46fe-b8d6-dfd4ab0b73b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Temp question' or . = 'Temp question')]</value>
      <webElementGuid>0cae3e66-67de-415b-8b9d-53dbf8631dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
