<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Description</name>
   <tag></tag>
   <elementGuidId>0bcb9e84-1628-4c47-8b7d-215650248faf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mainAnsExp > div.note-editor.note-frame.card > div.note-editing-area > div.note-editable.card-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div/div[2]/div/div[6]/div[2]/div[3]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>145c1df7-0a11-4bc5-aa49-0ad256d6c6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editable card-block</value>
      <webElementGuid>df77ea0b-6134-4b89-b767-27a3dc84a797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>82395d47-6b17-4451-874f-718f05879aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>da57e1ea-8a46-4ad9-99d8-af8135f149ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5878a011-19a4-4397-91bb-b875e398e68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7c63998-5cff-4914-82d5-89fb44650014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f36111a9-981a-4dc0-b999-18e2aa957891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>e475168b-1701-480d-ac92-435b5588ed2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-main&quot;]/div[@class=&quot;template_section shadow&quot;]/div[@class=&quot;mainAnsExp&quot;]/div[@class=&quot;note-editor note-frame card&quot;]/div[@class=&quot;note-editing-area&quot;]/div[@class=&quot;note-editable card-block&quot;]</value>
      <webElementGuid>25f5076f-d6b8-4b77-9655-bfdc801985ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[6]/div[2]/div[3]/div[3]</value>
      <webElementGuid>8aa13abf-24ac-436a-b74a-36f2199d5f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[3]/div[3]</value>
      <webElementGuid>62fa26bc-c396-46fb-960a-4460e5a53072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>ee770135-6c69-4688-9f5e-0926d3096094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
