<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_answer3</name>
   <tag></tag>
   <elementGuidId>0b5939a4-c11a-4846-955c-4293353f410e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#symboltext_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='symboltext_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6388b143-7588-4420-a262-77aa967b9e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f56196db-ffb0-437d-a1bd-6da38b0298c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control opt-text answer</value>
      <webElementGuid>44d6419d-1c2b-4cee-9e67-9f2ca66bb1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer[3]</value>
      <webElementGuid>89b08f5c-7f33-4d2a-8481-038892094be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>symboltext_3</value>
      <webElementGuid>f2a29531-b3a2-4e02-b450-7a3fc9de5341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;symboltext_3&quot;)</value>
      <webElementGuid>a9eb9dbe-844a-4c3a-9c26-e0b2d4914dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='symboltext_3']</value>
      <webElementGuid>ba2f0364-cd94-40d3-84de-29347b654282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCQ']/div[3]/div[4]/div/div/input</value>
      <webElementGuid>b71256b6-c640-42fc-be08-092bc9bfadd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>63642d16-d1d4-4114-851a-39da6802bf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'answer[3]' and @id = 'symboltext_3']</value>
      <webElementGuid>c3a47f04-f555-4944-8f29-658e9836b801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
