<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_answer_check</name>
   <tag></tag>
   <elementGuidId>91a5544c-0f93-417e-a70a-4cf28150718b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;answer_check&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='answer_check'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cec1506-3df0-4b2f-b5de-96d921bd58c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer_check</value>
      <webElementGuid>2cc4d515-e562-423d-a5a9-7a859586f12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>94eebaa0-dde1-4e87-becd-d1ad2416d030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>answer_check</value>
      <webElementGuid>32365ae9-09b9-4187-83a3-9140923ca795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MCQ&quot;)/div[@class=&quot;row opt-toggle opt-text&quot;]/div[@class=&quot;col-11 col-sm-11&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-prepend&quot;]/span[@class=&quot;input-group-text bg-light&quot;]/input[@class=&quot;answer_check&quot;]</value>
      <webElementGuid>ab3cb43e-d4b2-46c1-a9c6-356b0fbf028b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='answer_check']</value>
      <webElementGuid>133f493a-31c1-4d60-93df-b9ea6471aded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCQ']/div[3]/div/div/div/div/span/input</value>
      <webElementGuid>a3d3a62e-7ea9-49a0-9935-249f3d634007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7612c1c0-c602-4d70-9998-02f1d352c9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'answer_check' and @type = 'radio']</value>
      <webElementGuid>cccab50e-1e8e-4153-8818-a98f60b79c7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
