<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_answer2</name>
   <tag></tag>
   <elementGuidId>a29accca-92cd-433b-8e19-09d4372fbae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#symboltext_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='symboltext_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0598966f-42d4-4e33-9fd6-c6c2aac5f76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93b2cf77-d0e7-4f13-8318-8d2713c3233b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control opt-text answer</value>
      <webElementGuid>062ea13e-e707-454f-991b-72567996d94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer[2]</value>
      <webElementGuid>d2bf1562-920e-4d7f-b6a8-ad9c4af01580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>symboltext_2</value>
      <webElementGuid>f9f066ec-7fb0-4523-be2a-e1c9f2665c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;symboltext_2&quot;)</value>
      <webElementGuid>a21de29a-6501-4e4c-a8d2-5bf3d0775571</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='symboltext_2']</value>
      <webElementGuid>fc5e4e05-f28b-4f89-85b8-ef6bb0f7ac99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCQ']/div[3]/div[3]/div/div/input</value>
      <webElementGuid>fefd4c86-9c74-4411-84fa-22238435304e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>b8b26d05-ead6-46e2-967a-09bf722ace59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'answer[2]' and @id = 'symboltext_2']</value>
      <webElementGuid>0817f91a-1222-45b1-96ca-c96014e88dd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
