<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_answer1</name>
   <tag></tag>
   <elementGuidId>94716f69-831b-42f2-84b5-e0a9bb73db6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#symboltext_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='symboltext_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>746c25f8-ecbc-4fae-8a0e-d1fa63ac98cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db83d1e5-d6ce-4530-b7e9-92b24caf4732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control opt-text answer</value>
      <webElementGuid>e2067550-5f1e-4ad6-ae99-fbca5d0706a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer[1]</value>
      <webElementGuid>8396e5c2-e780-499c-8cc6-3191e098a793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>symboltext_1</value>
      <webElementGuid>a6093d39-de63-4789-8d92-0600f66ee2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;symboltext_1&quot;)</value>
      <webElementGuid>21a528e0-6d1b-43f6-8662-b9a17ad415e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='symboltext_1']</value>
      <webElementGuid>9f876ec6-c1f1-4ceb-96e5-3818865deb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCQ']/div[3]/div[2]/div/div/input</value>
      <webElementGuid>ba64ba2e-e32c-49b5-939d-d88632ec770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>31ff335b-d6f0-455a-a73d-0b0dad7ec55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'answer[1]' and @id = 'symboltext_1']</value>
      <webElementGuid>5867a031-a6c3-4f5c-879c-3b27545d44f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
