<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_answer0</name>
   <tag></tag>
   <elementGuidId>4a3ec2fb-44a4-442b-b203-dd2d6a3a4ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#symboltext_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='symboltext_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11ac3e9b-2bd2-475e-a550-46fa32fb21f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8881aebe-b7b5-4dd3-975c-5718b8ef612e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control opt-text answer</value>
      <webElementGuid>aa2ba2bd-0497-4fb6-89f5-c22f040994cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer[0]</value>
      <webElementGuid>d8af77c2-b947-478f-a4a9-6138a42b34ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>symboltext_0</value>
      <webElementGuid>5345bd73-59de-4c46-8c00-2d7ed54ed60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;symboltext_0&quot;)</value>
      <webElementGuid>da2dde62-87cb-49f4-9bdf-c858d3480324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='symboltext_0']</value>
      <webElementGuid>86af890d-8434-4f01-b82e-36698a119215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCQ']/div[3]/div/div/div/input</value>
      <webElementGuid>3b5b5b70-99ac-452e-bdea-6b4be012090d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>ba7615a2-aad6-4e65-88fb-1d148399f32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'answer[0]' and @id = 'symboltext_0']</value>
      <webElementGuid>5097d169-c5f2-445e-aeb7-9827f5486713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
