<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_flashcard_name</name>
   <tag></tag>
   <elementGuidId>e2c091e8-8bb6-4a6c-924d-11c67744c61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flashcard_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flashcard_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aca0682-c997-4394-816e-c92e68229c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14a6c730-f83e-412c-9957-d2ba29641983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cbc777d4-1921-4edd-8289-fbbcd97429cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flashcard_name</value>
      <webElementGuid>af667c23-445e-46f6-abbe-e2a2c11cd2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flashcard_name</value>
      <webElementGuid>03c174f8-d58b-4dc3-bad5-7bb1502a7850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>duplicateFlashcardName(this)</value>
      <webElementGuid>ab69d004-50c2-467f-867a-bdfea5b63eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flashcard_name&quot;)</value>
      <webElementGuid>902be4f9-68f9-4e80-9c67-b3903a554875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flashcard_name']</value>
      <webElementGuid>8136db5c-0ab1-4c45-a152-e7204d2bd2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[4]/div/input</value>
      <webElementGuid>56a545ac-ecb0-44c0-becc-c658f9edd69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a9d5b7db-c44f-4bb6-bfd9-57f553bf5d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'flashcard_name' and @id = 'flashcard_name']</value>
      <webElementGuid>669195a6-230a-458a-a618-0e4450889a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
