<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AlgebraPercentageRatioRate  SpeedAre_17f989</name>
   <tag></tag>
   <elementGuidId>b4a59157-d3a7-44bd-b430-9c517afe7931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='topic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34fb15ea-c3fe-451f-a8d4-d11c3ad5018f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>59e440b1-e188-416a-bea7-a26474b99744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>0d3e2c7a-33ce-44c5-87e9-ee7c24efecd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>51ea0e34-c8b1-4ae6-88dd-b078e88e826f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AlgebraPercentageRatioRate &amp; SpeedArea &amp; VolumeFractionsGeometryData Representation &amp; Interpretation</value>
      <webElementGuid>5e8ceae8-b3b2-43c3-a0b5-ee7d0e94c98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topic&quot;)</value>
      <webElementGuid>b8f7f5fa-418f-485c-9dfd-9c80a1e13b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='topic']</value>
      <webElementGuid>68f75527-483e-4c68-acab-9bcafa393ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[3]/div/select</value>
      <webElementGuid>91006f95-3cba-4dca-9aba-d8ec8d159654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>1aecdc0b-2c3f-4ee8-b3e3-846c6fbfca3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'topic' and @id = 'topic' and (text() = 'AlgebraPercentageRatioRate &amp; SpeedArea &amp; VolumeFractionsGeometryData Representation &amp; Interpretation' or . = 'AlgebraPercentageRatioRate &amp; SpeedArea &amp; VolumeFractionsGeometryData Representation &amp; Interpretation')]</value>
      <webElementGuid>670bdbf5-5f2d-4520-910a-b361af1e377a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
