<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Studysmart_icon</name>
   <tag></tag>
   <elementGuidId>a7040f73-1475-4e9a-99e8-18251d99b205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='bgTransparent']/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.brand-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>829c37ec-fe27-4f8e-a9bb-2cf270b0511d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qc.studysmart.sg/resource/img/logo.png</value>
      <webElementGuid>221f5ad7-dd87-4866-b3ec-316281c3f9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>14d764f8-712a-4ed5-b1b4-486ee2a24d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-image</value>
      <webElementGuid>2ac47a80-773e-4fdd-a4ef-40892a2d945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bgTransparent&quot;)/a[@class=&quot;brand-link&quot;]/img[@class=&quot;brand-image&quot;]</value>
      <webElementGuid>6cce56cc-e681-4d7a-a1be-54ebe3794296</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='bgTransparent']/a/img</value>
      <webElementGuid>22534e1e-5250-4156-9631-ab0162d30086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo']</value>
      <webElementGuid>2026b10b-8e3c-4d56-8ade-4f1ab904dd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/a/img</value>
      <webElementGuid>edec03a3-8f41-47c1-baed-915c91233586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qc.studysmart.sg/resource/img/logo.png' and @alt = 'Logo']</value>
      <webElementGuid>9e271b14-7d8e-4a5f-a7c8-5b88b435ddce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
