<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_custom-control-label</name>
   <tag></tag>
   <elementGuidId>3ef15a69-79a2-4921-95a3-e1214ae08545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div/div[2]/div/div[6]/div/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.custom-control-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e69daab0-e235-421b-876c-763b4c369ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>b0b7c048-b6de-46dc-8e42-96d88c6cd1b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>e00724e9-35ea-49d7-8821-6ce3cf357f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;card shadow&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;custom-control custom-switch enable checkbox-success pt-2&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>abb42e23-454a-45ab-a2b2-a370928b61e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[6]/div/div[2]/label</value>
      <webElementGuid>aa94df6c-8c31-45b5-8c71-169cbb5dd328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>ba1bf225-6612-4bcf-97dc-85048623fe5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
