<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select--Topic--</name>
   <tag></tag>
   <elementGuidId>e841cb27-1a7b-40c2-80b0-3d8d3997ecb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='topic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>336fff65-4a3d-4269-9035-303fd67f5e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>8fa04d5c-cfac-4735-958a-e8606e529a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>a4d4e365-e02a-45b3-a3f6-7549e8d8238c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f18c9ea9-b5fe-4a49-86f8-cbc04b64264a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cell SystemElectrical SystemInteractions within the EnvironmentEnergy ConversionCycles in matter and WaterEnergy Forms and usesCycles in plants and AnimalsHuman SystemPlant SystemInteractions and forces</value>
      <webElementGuid>b7018b4c-2265-496e-8f5a-8c541b2badeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topic&quot;)</value>
      <webElementGuid>574143da-0786-4595-ab00-523abdd91bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='topic']</value>
      <webElementGuid>25c4540b-9397-4e76-a120-da4d3f2e0e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[3]/div/select</value>
      <webElementGuid>3b4df458-3f8a-4519-ba68-0c21502077ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>3f6913a8-7e41-4a85-a784-3f64f9ddc92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'topic' and @id = 'topic' and (text() = 'Cell SystemElectrical SystemInteractions within the EnvironmentEnergy ConversionCycles in matter and WaterEnergy Forms and usesCycles in plants and AnimalsHuman SystemPlant SystemInteractions and forces' or . = 'Cell SystemElectrical SystemInteractions within the EnvironmentEnergy ConversionCycles in matter and WaterEnergy Forms and usesCycles in plants and AnimalsHuman SystemPlant SystemInteractions and forces')]</value>
      <webElementGuid>c8cdc040-6f82-490c-9443-5a8033f17d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
