<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vocabulary Cloze MCQVisual Comprehen_671494</name>
   <tag></tag>
   <elementGuidId>9fa664cf-af0b-4029-8781-bbfc00185517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='topic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#topic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b0f17284-78aa-4a54-9e39-db73750bbef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>8450112c-c10b-440d-8152-f5ad7399e4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topic</value>
      <webElementGuid>5c8ff5c8-8cee-45e8-8b0f-1e904adf4435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a1c7276d-f4b3-45b3-8dd7-d1c077de24ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vocabulary Cloze MCQVisual Comprehension MCQGrammar Cloze Open-EndedEditing Passage Open-EndedComprehension Cloze Open-EndedSynthesis &amp; TransformationComprehension Open-EndedGrammar MCQVocabulary MCQ</value>
      <webElementGuid>4ba10f32-8556-418a-a228-14da7eefef67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topic&quot;)</value>
      <webElementGuid>09af6d73-9c62-4719-a93d-060019fed92a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='topic']</value>
      <webElementGuid>c03c315d-9ff1-4265-b2ad-3ad7853ee8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[2]/div/div[3]/div/select</value>
      <webElementGuid>762f1abd-04fa-499f-99ad-e7fc5b69d7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>0a06860b-597e-4e92-a8b5-caf2b7fa84b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'topic' and @id = 'topic' and (text() = 'Vocabulary Cloze MCQVisual Comprehension MCQGrammar Cloze Open-EndedEditing Passage Open-EndedComprehension Cloze Open-EndedSynthesis &amp; TransformationComprehension Open-EndedGrammar MCQVocabulary MCQ' or . = 'Vocabulary Cloze MCQVisual Comprehension MCQGrammar Cloze Open-EndedEditing Passage Open-EndedComprehension Cloze Open-EndedSynthesis &amp; TransformationComprehension Open-EndedGrammar MCQVocabulary MCQ')]</value>
      <webElementGuid>f798ec45-45f2-4ce6-98d9-3eb286c82cc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
